#!/usr/bin/env python3
"""Generate the Confidence Aviation website into public/.

Content rules
  * Every sentence taken from the original site is reproduced verbatim somewhere on the
    site (tools/inventory.json, checked by tools/audit.py).
  * New copy only restates, labels or organises facts that appear in the original site or
    in the certificate documents. No new claims. Anything uncertain is listed in
    docs/owner-verification-required.md, not "fixed" here.
  * English and Spanish pages are generated by the same functions (t(en, es)) so they
    carry the same facts, sections and calls to action.

Usage:  python3 tools/images.py && python3 tools/build.py && python3 tools/audit.py
"""
import datetime
import hashlib
import html
import json
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from documents import SPEC, TRANSCRIPT  # noqa: E402  (verbatim certificate data)

ROOT = Path(__file__).resolve().parent.parent
PUB = ROOT / "public"
SRC = ROOT / "src"
SITE = "https://www.confidenceaviation.com"      # single production origin: https + www
IMG = json.loads((SRC / "images.json").read_text())
YEAR = datetime.date.today().year

PHONE, PHONE_TEL = "1-305-392-6291", "tel:+13053926291"
FAX = "1-305-392-6292"
EMAIL = "info@confidenceaviation.com"
ADDRESS_LINES = ("Confidence Aviation, Inc.", "7605 N.W. 50th Street", "Miami, FL 33166")
FAA_RSS = "https://www.faa.gov/newsroom/press_releases/rss"
GMAPS_DIR = "https://www.google.com/maps/dir/?api=1&destination=7605+NW+50th+Street%2C+Miami%2C+FL+33166"
MAPQUEST = [("MIA", "http://mapq.st/mPYIIX"), ("FLL", "http://mapq.st/o5gaCs"), ("FXE", "http://mapq.st/oRBGHw")]

# Set to a page path (e.g. "privacy.htm") once the owner supplies a privacy policy;
# the footer link and sitemap entry appear automatically. Deliberately None for now:
# we do not publish invented privacy practices.
PRIVACY_PAGE = None

# Original <meta name="keywords">, verbatim. index.htm and about.htm used the first
# spelling ("avioncs"), the other pages the second.
KEYWORDS_A = ("FAA, certified, repair, station, OEM, boeing, avionics, avionics repair, L3, avioncs, Bendix, "
              "Honeywell, King, Sperry, ameri-cam, DME, aviation, auto pilot, transponder, T-CAS, aircraft "
              "antennas, weather radar, altimeter repair, collins")
KEYWORDS_B = KEYWORDS_A.replace("L3, avioncs", "L3, avionics")

PAGES = ["home", "about", "capabilities", "certificates", "shop", "contact"]
FILES = {"home": "index.html", "about": "about.htm", "capabilities": "capabilities.htm",
         "certificates": "certificates.htm", "shop": "shop.htm", "contact": "contact.htm"}


def url(lang, page, frag=""):
    prefix = "/es/" if lang == "es" else "/"
    return (prefix if page == "home" else prefix + FILES[page]) + (f"#{frag}" if frag else "")


LANG_EN = ' lang="en"'


def e(s):
    return html.escape(s, quote=True)


def tr(lang):
    """t(en, es) -> the string for this language."""
    return lambda en, es: en if lang == "en" else es


# ---------------------------------------------------------------- images
def picture(slug, alt, *, sizes="100vw", lazy=True, cls="", priority=False, max_w=None):
    info = IMG[slug]
    variants = sorted(info["sizes"], key=lambda s: s["w"])
    if max_w:
        variants = [v for v in variants if v["w"] <= max_w] or variants[:1]
    big = variants[-1]
    fb = big["fallback"]
    webp = ", ".join(f"/assets/img/{slug}-{v['w']}.webp {v['w']}w" for v in variants)
    fall = ", ".join(f"/assets/img/{slug}-{v['w']}.{fb} {v['w']}w" for v in variants)
    attrs = ' loading="lazy" decoding="async"' if lazy else ' decoding="async"'
    if priority:
        attrs += ' fetchpriority="high"'
    c = f' class="{cls}"' if cls else ""
    return (f'<picture><source type="image/webp" srcset="{webp}" sizes="{sizes}">'
            f'<img src="/assets/img/{slug}-{big["w"]}.{fb}" srcset="{fall}" sizes="{sizes}" '
            f'width="{big["w"]}" height="{big["h"]}" alt="{e(alt)}"{c}{attrs}></picture>')


def full_src(slug):
    big = max(IMG[slug]["sizes"], key=lambda s: s["w"])
    return f"/assets/img/{slug}-{big['w']}.{big['fallback']}"


# ---------------------------------------------------------------- icons (inline SVG sprite, stroke only)
ICONS = {
    "radio": "M12 21v-9M9 21h6M10.6 10.6a2 2 0 1 1 2.8 0M8.2 7.4a5.3 5.3 0 0 0 0 7.2M15.8 7.4a5.3 5.3 0 0 1 0 7.2M5.5 4.8a9 9 0 0 0 0 12.4M18.5 4.8a9 9 0 0 1 0 12.4",
    "nav": "M12 3a9 9 0 1 1 0 18a9 9 0 1 1 0-18zM15.5 8.5l-2 5-5 2 2-5z",
    "radar": "M12 3a9 9 0 1 1 0 18a9 9 0 1 1 0-18zM12 7a5 5 0 1 1 0 10a5 5 0 1 1 0-10zM12 12l6.4-6.4",
    "valve": "M4 7v10l8-5zM20 7v10l-8-5zM12 12V5M9 4.5h6",
    "gauge": "M4 17a8 8 0 1 1 16 0M12 17l4.2-5.2M6.6 12.4l1.2.8M12 9v1.4M17.4 12.4l-1.2.8M3.5 17h17",
    "doc": "M7 3h7l4 4v14H7zM14 3v4h4M9.5 12h5M9.5 15h5M9.5 18h3",
    "globe": "M12 3a9 9 0 1 1 0 18a9 9 0 1 1 0-18zM3 12h18M12 3c3 3.2 3 14.8 0 18M12 3c-3 3.2-3 14.8 0 18",
    "calendar": "M4 6h16v14H4zM4 10h16M8 3v4M16 3v4",
    "wrench": "M14.7 6.3a4 4 0 0 0-5.3 5.2L4 16.9 7.1 20l5.4-5.4a4 4 0 0 0 5.2-5.3l-2.4 2.4-2.4-.6-.6-2.4z",
    "scope": "M3 5h18v12H3zM6 13l2.5-4 3 5 3-6 3.5 5M8 21h8M12 17v4",
    "pin": "M12 21s-7-6.2-7-11a7 7 0 0 1 14 0c0 4.8-7 11-7 11zM12 7.5a2.5 2.5 0 1 1 0 5a2.5 2.5 0 1 1 0-5z",
    "phone": "M5 4h3.5l2 5-2.4 1.5a11 11 0 0 0 5.4 5.4L15 13.5l5 2V19a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z",
    "mail": "M3 6h18v12H3zM3 7l9 6.2L21 7",
    "arrow": "M5 12h14M13 6l6 6-6 6",
}


def icon(name, cls="icon"):
    return f'<svg class="{cls}" aria-hidden="true" focusable="false"><use href="#i-{name}"></use></svg>'


SPRITE = ('<svg class="sprite" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg">'
          + "".join(f'<symbol id="i-{k}" viewBox="0 0 24 24"><path d="{v}"/></symbol>' for k, v in ICONS.items())
          + "</svg>")


# ---------------------------------------------------------------- shared data
SHOP = [  # (anchor/slug, original caption (alt/title on old site), Spanish caption, EN alt, ES alt)
    ("shop-entrance", "Aviation Workshop Entrance", "Taller de aviación: entrada",
     "View from the shop entrance of workbenches lined with electronic test equipment",
     "Vista desde la entrada del taller de bancos de trabajo con equipos electrónicos de prueba"),
    ("shop-dme-transponder-bench", "Aviation Workshop DME Transponder Bench", "Taller de aviación: banco de DME y transpondedor",
     "Workbench with oscilloscopes and test instruments at the DME transponder bench",
     "Banco de trabajo con osciloscopios e instrumentos de prueba en el banco de DME y transpondedor"),
    ("shop-radar-bench-1", "Aviation Workshop Radar Bench 1", "Taller de aviación: banco de radar 1",
     "Radar test bench with instruments, a unit on the bench and an open manual",
     "Banco de prueba de radar con instrumentos, una unidad en el banco y un manual abierto"),
    ("shop-nav-comm-bench", "Aviation Workshop NAV/COMM Bench", "Taller de aviación: banco NAV/COMM",
     "NAV/COMM bench with racks of test instruments and an open manual",
     "Banco NAV/COMM con estantes de instrumentos de prueba y un manual abierto"),
    ("shop-radar-bench-2", "Aviation Workshop Radar Bench 2", "Taller de aviación: banco de radar 2",
     "Radar bench with components and tools laid out on the work surface",
     "Banco de radar con componentes y herramientas sobre la superficie de trabajo"),
    ("shop-dme-altimeter-benches", "Aviation Workshop DME & Altimeter Benches", "Taller de aviación: bancos de DME y altímetro",
     "Row of benches with test equipment and a test rack",
     "Fila de bancos con equipos de prueba y un bastidor de pruebas"),
    ("shop-radar-nav-comm-bench", "Aviation Workshop Radar & NAV Comm Bench 2", "Taller de aviación: banco de radar y NAV/COMM 2",
     "Radar and NAV/COMM bench with test instruments",
     "Banco de radar y NAV/COMM con instrumentos de prueba"),
    ("shop-altimeter-test-set", "Aviation Workshop Altimeter Test Set", "Taller de aviación: equipo de prueba de altímetros",
     "Altimeter test set rack with meters, switches and a connection panel",
     "Bastidor del equipo de prueba de altímetros con medidores, interruptores y panel de conexiones"),
    ("shop-hf-antenna", "Aviation Workshop HF Antenna", "Taller de aviación: antena HF",
     "HF antenna equipment and avionics units on a bench",
     "Equipo de antena HF y unidades de aviónica sobre un banco"),
    ("shop-radar-indicators", "Aviation Workshop Radar Indicators", "Taller de aviación: indicadores de radar",
     "Several radar indicator display units stacked on a bench",
     "Varias unidades indicadoras de radar apiladas sobre un banco"),
    ("shop-large-radar-system", "Aviation Workshop Large Radar System", "Taller de aviación: sistema de radar grande",
     "Large radar system with its antenna dish on a bench",
     "Sistema de radar grande con su antena parabólica sobre un banco"),
    ("shop-radio-altimeters", "Aviation Workshop Radio Altimeters", "Taller de aviación: radioaltímetros",
     "Radio altimeter units stacked on a bench",
     "Unidades de radioaltímetro apiladas sobre un banco"),
]
SHOP_BY_SLUG = {s[0]: s for s in SHOP}

# (anchor/slug, original title, original file, Spanish title, short id, date as printed EN, ES)
DOCS = [
    ("air-agency-certificate", "Air Agency Certificate", "air_agency_certificate.gif",
     "Certificado de Agencia Aérea (FAA)", "No. V9DR072Y",
     "Date issued: December 15, 1998", "Fecha de emisión: 15 de diciembre de 1998"),
    ("easa-approval-certificate", "European Aviation Safety Agency Approval Certificate", "easa-cert.jpg",
     "Certificado de aprobación de la Agencia Europea de Seguridad Aérea", "EASA.145.5139",
     "Date of issue: 19 October 2004", "Fecha de emisión: 19 de octubre de 2004"),
    ("operations-specifications", "Operations Specifications", "operations_specifications.gif",
     "Especificaciones de operación (FAA)", "A003",
     "Approval effective: 1/22/03 (Amendment 2)", "Vigencia de la aprobación: 22/01/2003 (enmienda 2)"),
]
DOC_ISSUER = {
    "air-agency-certificate": ("FAA (U.S. Department of Transportation)", "FAA (Departamento de Transporte de EE. UU.)"),
    "easa-approval-certificate": ("European Aviation Safety Agency (EASA)", "Agencia Europea de Seguridad Aérea (EASA)"),
    "operations-specifications": ("FAA (U.S. Department of Transportation)", "FAA (Departamento de Transporte de EE. UU.)"),
}

# What we repair: only categories documented on the original site.
# (anchor on capabilities page, icon, EN title, ES title, EN basis, ES basis)
CAPS = [
    ("communications", "radio", "Communications Equipment", "Equipos de comunicaciones",
     "FAA Radio Class 1 rating (unlimited)", "Habilitación FAA Radio Class 1 (ilimitada)"),
    ("navigation", "nav", "Navigational Equipment", "Equipos de navegación",
     "FAA Radio Class 2 rating (unlimited)", "Habilitación FAA Radio Class 2 (ilimitada)"),
    ("radar", "radar", "Radar Equipment", "Equipos de radar",
     "FAA Radio Class 3 rating (unlimited)", "Habilitación FAA Radio Class 3 (ilimitada)"),
    ("accessories", "valve", "Accessories", "Accesorios",
     "Limited Ratings: many accessories including pneumatic valves and lights",
     "Habilitaciones limitadas: muchos accesorios, incluidas válvulas neumáticas y luces"),
    ("avionics-instruments", "gauge", "Avionics & Instruments", "Aviónica e instrumentos",
     "OEM alternative repairs for Boeing, Bendix/King, Honeywell, Sperry and Collins aircraft instrument panels and valves",
     "Reparaciones como alternativa al OEM para paneles de instrumentos y válvulas de aeronaves Boeing, Bendix/King, Honeywell, Sperry y Collins"),
]

UI = {
    "en": {
        "nav": {"home": "Home", "about": "About Us", "capabilities": "Capabilities",
                "certificates": "Certificates", "shop": "Shop Tour", "contact": "Contact"},
        "cta": "Request a Repair Quote", "cta_short": "Request a Quote",
        "skip": "Skip to main content", "menu": "Menu", "main_nav": "Main navigation",
        "lang_label": "Language Option", "brand_alt": "Confidence Aviation, Inc.",
        "home_link": "Confidence Aviation, Inc. — home",
        "tag": "Avionics & Instruments — FAA Certified Repair Station",
        "phone": "Phone", "fax": "Fax", "email": "Email",
        "f_contact": "Contact", "f_pages": "Pages", "f_docs": "Certificates", "f_lang": "Language Option",
        "breadcrumb": "Breadcrumb", "repair_no": "FAA Repair Station No.",
        "og_locale": "en_US", "quick": "Quick contact and language",
        "directions": "Directions", "headlines": "Aviation Headlines",
        "faa_feed": "FAA newsroom press releases (RSS)", "privacy": "Privacy Policy",
        "easa_ref": "EASA approval ref.", "doc_2004": "document dated 2004",
        "miami": "Miami, Florida",
    },
    "es": {
        "nav": {"home": "Inicio", "about": "Nosotros", "capabilities": "Capacidades",
                "certificates": "Certificados", "shop": "Recorrido del taller", "contact": "Contacto"},
        "nav_header": {"shop": "Taller"},   # shorter label so the Spanish header fits on one line
        "cta": "Solicitar cotización de reparación", "cta_short": "Solicitar cotización",
        "skip": "Saltar al contenido principal", "menu": "Menú", "main_nav": "Navegación principal",
        "lang_label": "Idioma", "brand_alt": "Confidence Aviation, Inc.",
        "home_link": "Confidence Aviation, Inc. — inicio",
        "tag": "Aviónica e instrumentos — Estación reparadora certificada por la FAA",
        "phone": "Teléfono", "fax": "Fax", "email": "Correo electrónico",
        "f_contact": "Contacto", "f_pages": "Páginas", "f_docs": "Certificados", "f_lang": "Idioma",
        "breadcrumb": "Ruta de navegación", "repair_no": "Estación reparadora FAA No.",
        "og_locale": "es_ES", "quick": "Contacto rápido e idioma",
        "directions": "Cómo llegar", "headlines": "Noticias de aviación",
        "faa_feed": "Comunicados de prensa de la FAA (RSS, en inglés)", "privacy": "Política de privacidad",
        "easa_ref": "Ref. de aprobación EASA", "doc_2004": "documento de 2004",
        "miami": "Miami, Florida",
    },
}


# ---------------------------------------------------------------- structured data
def org_node(lang):
    return {
        "@type": "LocalBusiness",
        "@id": SITE + "/#organization",
        "name": "Confidence Aviation, Inc.",
        "url": SITE + "/",
        "logo": SITE + "/assets/img/logo-800.png",
        "image": SITE + "/assets/img/shop-entrance-497.jpg",
        "description": ("FAA / EASA certified repair station offering overhaul and repair capabilities "
                        "for avionics and instruments. FAA repair station No. V9DR072Y.") if lang == "en" else (
                        "Estación reparadora certificada por la FAA / EASA con capacidades de reparación general "
                        "(overhaul) y reparación de aviónica e instrumentos. Estación reparadora FAA No. V9DR072Y."),
        "foundingDate": "1998",
        "telephone": "+1-305-392-6291",
        "faxNumber": "+1-305-392-6292",
        "email": EMAIL,
        "identifier": {"@type": "PropertyValue", "propertyID": "FAA Air Agency Certificate (repair station) number",
                       "value": "V9DR072Y"},
        "address": {"@type": "PostalAddress", "streetAddress": "7605 N.W. 50th Street",
                    "addressLocality": "Miami", "addressRegion": "FL", "postalCode": "33166",
                    "addressCountry": "US"},
    }


def jsonld(lang, page, title, desc, crumbs):
    canonical = SITE + url(lang, page)
    graph = [org_node(lang),
             {"@type": "WebSite", "@id": SITE + "/#website", "url": SITE + "/", "name": "Confidence Aviation, Inc.",
              "inLanguage": ["en", "es"], "publisher": {"@id": SITE + "/#organization"}},
             {"@type": "WebPage", "@id": canonical + "#webpage", "url": canonical, "name": title,
              "description": desc, "inLanguage": lang, "isPartOf": {"@id": SITE + "/#website"},
              "about": {"@id": SITE + "/#organization"}}]
    if crumbs:
        home = UI[lang]["nav"]["home"]
        graph.append({"@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": SITE + h}
            for i, (n, h) in enumerate([(home, url(lang, "home"))] + crumbs)]})
        graph[2]["breadcrumb"] = {"@id": canonical + "#breadcrumb"}
        graph[-1]["@id"] = canonical + "#breadcrumb"
    return json.dumps({"@context": "https://schema.org", "@graph": graph}, ensure_ascii=False)


# ---------------------------------------------------------------- layout
def lang_switch(lang, page):
    en_cur = ' aria-current="true"' if lang == "en" else ""
    es_cur = ' aria-current="true"' if lang == "es" else ""
    es_text = 'Español<span class="visually-hidden"> (Spanish)</span>' if lang == "en" else "Español"
    return (f'<span class="lang"><span class="lang__label">{UI[lang]["lang_label"]}:</span> '
            f'<a href="{url("en", page)}" hreflang="en" lang="en"{en_cur}>English</a>'
            f'<span aria-hidden="true">/</span><a href="{url("es", page)}" hreflang="es" lang="es"{es_cur}>{es_text}</a></span>')


def layout(lang, page, *, title, desc, body, crumbs=None, keywords=KEYWORDS_B, og_image=None, noindex=False):
    u, t = UI[lang], tr(lang)
    canonical = SITE + url(lang, page)
    cur = ' aria-current="page"'
    nav = "".join(f'<li><a href="{url(lang, p)}"{cur if p == page and not noindex else ""}>{u.get("nav_header", {}).get(p, u["nav"][p])}</a></li>'
                  for p in PAGES)
    og_img = SITE + (og_image or "/assets/img/shop-entrance-497.jpg")
    crumb_html = ""
    if crumbs:
        items = [f'<li><a href="{url(lang, "home")}">{u["nav"]["home"]}</a></li>']
        items += [f'<li><a href="{h}" aria-current="page">{e(n)}</a></li>' for n, h in crumbs]
        crumb_html = f'<nav class="breadcrumb" aria-label="{u["breadcrumb"]}"><ol>{"".join(items)}</ol></nav>'
    body = body.replace("{{CRUMBS}}", crumb_html)
    alt_locale = "es_ES" if lang == "en" else "en_US"
    if noindex:
        index_tags = '<meta name="robots" content="noindex">'
        ld = ""
    else:
        index_tags = (f'<link rel="canonical" href="{canonical}">\n'
                      f'<link rel="alternate" hreflang="en" href="{SITE + url("en", page)}">\n'
                      f'<link rel="alternate" hreflang="es" href="{SITE + url("es", page)}">\n'
                      f'<link rel="alternate" hreflang="x-default" href="{SITE + url("en", page)}">')
        ld = f'<script type="application/ld+json">{jsonld(lang, page, title, desc, crumbs)}</script>'
    footer_lang = (f'<a href="{url("en", page)}" hreflang="en" lang="en">English</a> / '
                   f'<a href="{url("es", page)}" hreflang="es" lang="es">'
                   + ("Spanish (Español)" if lang == "en" else "Español") + "</a>")
    privacy = (f'<li><a href="/{"es/" if lang == "es" else ""}{PRIVACY_PAGE}">{u["privacy"]}</a></li>'
               if PRIVACY_PAGE else "")
    docs_links = "".join(f'<li><a href="{url(lang, "certificates", slug)}">{title if lang == "en" else es}</a></li>'
                         for slug, title, _o, es, *_ in DOCS)
    return f"""<!doctype html>
<html lang="{lang}" class="no-js">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
<meta name="keywords" content="{e(keywords)}">
{index_tags}
<meta property="og:type" content="website">
<meta property="og:site_name" content="Confidence Aviation, Inc.">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:url" content="{canonical}">
<meta property="og:image" content="{og_img}">
<meta property="og:image:alt" content="{e(t('Confidence Aviation shop', 'Taller de Confidence Aviation'))}">
<meta property="og:locale" content="{u['og_locale']}">
<meta property="og:locale:alternate" content="{alt_locale}">
<meta name="twitter:card" content="summary">
<meta name="theme-color" content="#03204a">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" href="/favicon.png" type="image/png" sizes="32x32">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="stylesheet" href="/assets/css/site.css?v={ASSET_V['css']}">
<script>document.documentElement.className="js"</script>
<script src="/assets/js/site.js?v={ASSET_V['js']}" defer></script>
{ld}
</head>
<body>
{SPRITE}
<a class="skip-link" href="#main">{u['skip']}</a>
<aside class="topbar" aria-label="{u['quick']}">
  <div class="wrap topbar__inner">
    <p class="topbar__ids"><span>{u['repair_no']} <span class="mono">V9DR072Y</span></span><span>{u['miami']}</span></p>
    <div class="topbar__contact">
      <a href="{PHONE_TEL}">{icon('phone', 'icon icon--sm')}{PHONE}</a>
      <a href="mailto:{EMAIL}">{icon('mail', 'icon icon--sm')}{EMAIL}</a>
      {lang_switch(lang, page)}
    </div>
  </div>
</aside>
<header class="site-header">
  <div class="wrap site-header__inner">
    <a class="brand" href="{url(lang, 'home')}" aria-label="{u['home_link']}">
      <picture><source type="image/webp" srcset="/assets/img/logo-400.webp 1x, /assets/img/logo-800.webp 2x"><img src="/assets/img/logo-400.png" srcset="/assets/img/logo-800.png 2x" width="400" height="59" alt="{u['brand_alt']}"></picture>
    </a>
    <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span class="nav-toggle__bars" aria-hidden="true"></span>{u['menu']}</button>
    <nav class="site-nav" id="site-nav" aria-label="{u['main_nav']}">
      <ul>{nav}</ul>
      <a class="btn btn--primary btn--sm header-cta" href="{url(lang, 'contact', 'quote')}">{u['cta_short']}</a>
    </nav>
  </div>
</header>
<main id="main" tabindex="-1">
{body}
</main>
<footer class="site-footer">
  <div class="wrap">
    <div class="footer-grid">
      <div>
        <p class="footer-name">Confidence Aviation, Inc.</p>
        <p>{u['tag']}</p>
        <p>{u['repair_no']} <span class="mono">V9DR072Y</span><br>{u['easa_ref']} <span class="mono">EASA.145.5139</span> ({u['doc_2004']})</p>
      </div>
      <div>
        <h2>{u['f_contact']}</h2>
        <address>{"<br>".join(ADDRESS_LINES)}</address>
        <ul>
          <li>{u['phone']}: <a href="{PHONE_TEL}">{PHONE}</a></li>
          <li>{u['fax']}: {FAX}</li>
          <li>{u['email']}: <a href="mailto:{EMAIL}">{EMAIL}</a></li>
          <li><a href="{url(lang, 'contact', 'directions')}">{u['directions']}</a></li>
        </ul>
      </div>
      <div>
        <h2>{u['f_pages']}</h2>
        <ul>{"".join(f'<li><a href="{url(lang, p)}">{u["nav"][p]}</a></li>' for p in PAGES)}</ul>
      </div>
      <div>
        <h2>{u['f_docs']}</h2>
        <ul>{docs_links}</ul>
        <h2 class="footer-h2-spaced">{u['headlines']}</h2>
        <ul><li><a href="{FAA_RSS}" rel="noopener"{' hreflang="en"' if lang == 'es' else ''}>{u['faa_feed']}</a></li></ul>
      </div>
    </div>
    <div class="footer-bottom">
      <p>© 2003–{YEAR} Confidence Aviation, Inc.</p>
      <ul class="footer-meta">{privacy}<li><span>{u['f_lang']}:</span> {footer_lang}</li></ul>
    </div>
  </div>
</footer>
</body>
</html>
"""


def page_head(eyebrow, h1, lead="", actions=""):
    lead_html = f'<p class="lead">{lead}</p>' if lead else ""
    act = f'<div class="actions">{actions}</div>' if actions else ""
    return (f'<div class="page-head"><div class="wrap">{{{{CRUMBS}}}}<span class="eyebrow">{eyebrow}</span>'
            f'<h1>{h1}</h1>{lead_html}{act}</div></div>')


def cta_buttons(lang, secondary=None):
    t = tr(lang)
    out = f'<a class="btn btn--primary" href="{url(lang, "contact", "quote")}">{UI[lang]["cta"]}</a>'
    if secondary:
        label, href = secondary
        out += f'<a class="btn btn--outline" href="{href}">{label}</a>'
    return out


def quote_band(lang, heading=None):
    """Consistent end-of-page call to action."""
    t = tr(lang)
    heading = heading or UI[lang]["cta"]
    return f"""
<section class="section section--dark on-dark quote-band" aria-labelledby="quote-band-h">
  <div class="wrap quote-band__grid">
    <div>
      <h2 id="quote-band-h">{heading}</h2>
      <p>{t("Include the manufacturer, model, part number, serial number, quantity and the work requested.",
            "Incluya el fabricante, el modelo, el número de parte, el número de serie, la cantidad y el trabajo solicitado.")}</p>
      <div class="actions">{cta_buttons(lang)}<a class="btn btn--outline" href="{PHONE_TEL}">{icon('phone', 'icon icon--sm')}{t('Call', 'Llamar al')} {PHONE}</a></div>
    </div>
    <address class="quote-band__addr">{icon('pin')}<span>{"<br>".join(ADDRESS_LINES)}<br><a href="mailto:{EMAIL}">{EMAIL}</a></span></address>
  </div>
</section>"""


def ratings_list(lang):
    """The three class ratings, verbatim ("Radio Class 1: Communications Equipment (unlimited)")."""
    t = tr(lang)
    rows = [("communications", "radio", "Radio Class 1:", "Communications Equipment", "Equipos de comunicaciones"),
            ("navigation", "nav", "Radio Class 2:", "Navigational Equipment", "Equipos de navegación"),
            ("radar", "radar", "Radio Class 3:", "Radar Equipment", "Equipos de radar")]
    if lang == "en":
        items = "".join(f'<li id="{a}">{icon(i)}<span class="r-class">{c}</span> <span class="r-scope">{s}</span> '
                        f'<span class="r-limit">(unlimited)</span></li>' for a, i, c, s, _ in rows)
    else:
        items = "".join(f'<li id="{a}">{icon(i)}<span class="r-class" lang="en">{c}</span> <span class="r-scope">{es} '
                        f'<span lang="en">({s})</span></span> <span class="r-limit">(ilimitada / <span lang="en">unlimited</span>)</span></li>'
                        for a, i, c, s, es in rows)
    return f'<ul class="ratings">{items}</ul>'


def gallery(lang, items, group, *, compact=False, link_to=None, with_ids=False, eager=0):
    out = []
    for i, (slug, cap_en, cap_es, alt_en, alt_es) in enumerate(items):
        cap = cap_en if lang == "en" else cap_es
        alt = alt_en if lang == "en" else alt_es
        sizes = "(max-width: 560px) 100vw, (max-width: 1100px) 33vw, 280px"
        pic = picture(slug, alt, sizes=sizes, lazy=i >= eager, priority=eager and i == 0)
        href = link_to + "#" + slug if link_to else full_src(slug)
        lb = "" if link_to else f' data-lightbox="{group}" data-caption="{e(cap)}"'
        idattr = f' id="{slug}"' if with_ids else ""
        en_cap = f' <span class="visually-hidden" lang="en">({cap_en})</span>' if lang == "es" and not compact else ""
        out.append(f'<li{idattr}><figure><a href="{href}"{lb}>{pic}</a><figcaption>{e(cap)}{en_cap}</figcaption></figure></li>')
    return f'<ul class="gallery{" gallery--compact" if compact else ""}">{"".join(out)}</ul>'


def doc_thumb(slug, alt, lazy=True):
    return picture(slug, alt, sizes="(max-width: 760px) 90vw, 320px", max_w=320, lazy=lazy)


def cap_cards(lang, link=True):
    t = tr(lang)
    cards = []
    for anchor, ic, en, es, b_en, b_es in CAPS:
        title = t(en, es)
        inner = (f'{icon(ic, "icon icon--lg")}<h3>{title}</h3><p>{t(b_en, b_es)}</p>')
        if link:
            inner += f'<span class="card__more" aria-hidden="true">{t("Details", "Detalles")} {icon("arrow", "icon icon--sm")}</span>'
            cards.append(f'<li><a class="cap-card" href="{url(lang, "capabilities", anchor)}">{inner}</a></li>')
        else:
            cards.append(f'<li><div class="cap-card">{inner}</div></li>')
    return f'<ul class="cap-grid">{"".join(cards)}</ul>'


# ---------------------------------------------------------------- pages
def home(lang):
    t = tr(lang)
    L = lambda p, f="": url(lang, p, f)  # noqa: E731
    why = [
        ("doc", t("FAA Repair Station No. V9DR072Y", "Estación reparadora FAA No. V9DR072Y"),
         t("Air Agency Certificate issued December 15, 1998, with RADIO and LIMITED ACCESSORY ratings.",
           "Air Agency Certificate emitido el 15 de diciembre de 1998, con las habilitaciones RADIO y LIMITED ACCESSORY."),
         L("certificates", "air-agency-certificate"), t("View the certificate", "Ver el certificado")),
        ("globe", t("EASA approval reference EASA.145.5139", "Referencia de aprobación EASA.145.5139"),
         t("European Aviation Safety Agency Approval Certificate, date of issue 19 October 2004.",
           "Certificado de aprobación de la Agencia Europea de Seguridad Aérea, fecha de emisión 19 de octubre de 2004."),
         L("certificates", "easa-approval-certificate"), t("View the document", "Ver el documento")),
        ("calendar", t("In business since 1998", "En actividad desde 1998"),
         t("Confidence Aviation opened its doors in 1998.", "Confidence Aviation abrió sus puertas en 1998."),
         L("about", "profile"), t("Company profile", "Perfil de la empresa")),
        ("wrench", t("Over 55 years of experience", "Más de 55 años de experiencia"),
         t("Our technicians have over 55 years of experience in aviation service.",
           "Nuestros técnicos tienen más de 55 años de experiencia en servicios de aviación."),
         L("about", "letter"), t("Read our Presidents’ message", "Leer el mensaje de nuestros presidentes")),
        ("scope", t("Documented test equipment", "Equipos de prueba documentados"),
         t("Shown in our shop tour: radar, NAV/COMM, DME transponder and altimeter benches and test sets.",
           "En el recorrido del taller: bancos y equipos de prueba de radar, NAV/COMM, DME/transpondedor y altímetros."),
         L("shop"), t("See the shop", "Ver el taller")),
        ("pin", t("Miami, Florida", "Miami, Florida"),
         t("7605 N.W. 50th Street, Miami, FL 33166, with directions from MIA, FLL and FXE airports.",
           "7605 N.W. 50th Street, Miami, FL 33166, con indicaciones desde los aeropuertos MIA, FLL y FXE."),
         L("contact", "directions"), t("Get directions", "Cómo llegar")),
    ]
    why_html = "".join(
        f'<li class="why-item">{icon(ic, "icon icon--lg")}<div><h3>{h}</h3><p>{p}</p>'
        f'<a class="more" href="{href}">{lab}</a></div></li>' for ic, h, p, href, lab in why)
    doc_cards = "".join(
        f'<li><a class="card card--link" href="{L("certificates", slug)}"><div class="card__media card__media--doc">'
        f'{doc_thumb(slug, t(title + " — scanned document", title + " — documento escaneado"))}</div>'
        f'<h3{LANG_EN if lang == "es" else ""}>{title}</h3>'
        f'{"" if lang == "en" else f"<p>{es}</p>"}<p class="mono">{short}</p><p class="doc-date">{t(d_en, d_es)}</p></a></li>'
        for slug, title, _o, es, short, d_en, d_es in DOCS)
    shop4 = [SHOP_BY_SLUG[s] for s in ("shop-radar-bench-1", "shop-nav-comm-bench", "shop-altimeter-test-set", "shop-radar-indicators")]

    body = f"""
<section class="hero on-dark" aria-labelledby="hero-title">
  <div class="wrap hero__grid">
    <div class="hero__copy">
      <span class="eyebrow">Confidence Aviation, Inc. · {t('Miami, Florida', 'Miami, Florida')}</span>
      <h1 id="hero-title">{t('Aircraft Avionics &amp; Instrument Repair', 'Reparación de aviónica e instrumentos de aeronaves')}</h1>
      <p class="lead">{t('We are an FAA / EASA certified repair station offering overhaul and repair capabilities.',
                         'Somos una estación reparadora certificada por la FAA / EASA que ofrece capacidades de reparación general (overhaul) y reparación.')}</p>
      <p class="hero__sub">{t('FAA ratings for communications, navigation and radar equipment, and limited ratings for accessories.',
                              'Habilitaciones de la FAA para equipos de comunicaciones, navegación y radar, y habilitaciones limitadas para accesorios.')}</p>
      <div class="actions">{cta_buttons(lang, (t('View Capabilities', 'Ver capacidades'), L('capabilities')))}</div>
      <p class="hero__contact">{t('Or call', 'O llame al')} <a href="{PHONE_TEL}">{PHONE}</a> · <a href="mailto:{EMAIL}">{EMAIL}</a></p>
    </div>
    <aside class="dataplate" aria-labelledby="dp-title">
      <p class="dataplate__title" id="dp-title">{t('Repair station at a glance', 'La estación reparadora en resumen')}</p>
      <dl>
        <dt>{t('FAA Air Agency Certificate', 'Certificado de Agencia Aérea FAA')}</dt><dd><span class="mono">V9DR072Y</span></dd>
        <dt>{t('Class ratings', 'Habilitaciones de clase')}</dt><dd>Radio Class 1, 2 {t('&amp;', 'y')} 3</dd>
        <dt>{t('Limited ratings', 'Habilitaciones limitadas')}</dt><dd>{t('Accessories', 'Accesorios')}</dd>
        <dt>{t('EASA approval ref.', 'Ref. de aprobación EASA')}</dt><dd><span class="mono">EASA.145.5139</span> <small>({t('issued 19 Oct 2004', 'emitido el 19 oct. 2004')})</small></dd>
        <dt>{t('Opened', 'Apertura')}</dt><dd>1998</dd>
        <dt>{t('Location', 'Ubicación')}</dt><dd>7605 N.W. 50th Street, Miami, FL 33166</dd>
      </dl>
      <a class="dataplate__link" href="{L('certificates')}">{t('View certificates', 'Ver certificados')} {icon('arrow', 'icon icon--sm')}</a>
    </aside>
  </div>
</section>

<section class="section" aria-labelledby="repair-title" id="what-we-repair">
  <div class="wrap">
    <div class="section__head">
      <div><span class="eyebrow">{t('Avionics &amp; Instruments', 'Aviónica e instrumentos')}</span><h2 id="repair-title">{t('What we repair', 'Qué reparamos')}</h2></div>
      <a class="more" href="{L('capabilities')}">{t('All capabilities', 'Todas las capacidades')}</a>
    </div>
    <p class="section__intro">{t('Confidence Aviation is authorized the following ratings and limitations:', 'Confidence Aviation está autorizada para las siguientes habilitaciones y limitaciones:')}</p>
    {cap_cards(lang)}
    <p class="note cap-note">{t(f'Please call our offices at <a href="{PHONE_TEL}">1-305-392-6291</a> for a complete list.',
                                f'Llame a nuestras oficinas al <a href="{PHONE_TEL}">1-305-392-6291</a> para obtener una lista completa.')}</p>
  </div>
</section>

<section class="section section--alt" aria-labelledby="why-title">
  <div class="wrap">
    <div class="section__head"><div><span class="eyebrow">{t('Credentials &amp; facility', 'Credenciales e instalaciones')}</span>
      <h2 id="why-title">{t('Why Confidence Aviation', 'Por qué Confidence Aviation')}</h2></div></div>
    <ul class="why-grid">{why_html}</ul>
  </div>
</section>

<section class="section" aria-labelledby="shop-title">
  <div class="wrap">
    <div class="section__head">
      <div><span class="eyebrow">{t('Shop Tour', 'Recorrido del taller')}</span><h2 id="shop-title">{t('Inside our shop', 'Nuestro taller')}</h2></div>
      <a class="more" href="{L('shop')}">{t('See the full shop tour', 'Ver el recorrido completo')}</a>
    </div>
    <div class="gallery-four">{gallery(lang, shop4, "home", compact=True)}</div>
  </div>
</section>

<section class="section section--alt" aria-labelledby="cert-title">
  <div class="wrap">
    <div class="section__head">
      <div><span class="eyebrow">FAA · EASA</span><h2 id="cert-title">{t('Certificates', 'Certificados')}</h2></div>
      <a class="more" href="{L('certificates')}">{t('View all certificates', 'Ver todos los certificados')}</a>
    </div>
    <ul class="grid-3 plain-list">{doc_cards}</ul>
    <p class="note">{t('Dates shown are those printed on each document. Contact us for current certification status.',
                       'Las fechas son las que figuran en cada documento. Contáctenos para conocer el estado actual de la certificación.')}</p>
  </div>
</section>

<section class="section" aria-labelledby="welcome-title">
  <div class="wrap split">
    <div class="prose welcome">
      <h2 id="welcome-title">{t('Welcome', 'Bienvenidos')}</h2>
      <p>{t('Confidence Aviation would like to welcome you to its website.', 'Confidence Aviation le da la bienvenida a su sitio web.')}</p>
      <p class="mono-line">{t('FAA repair station No. V9DR072Y', 'Estación reparadora FAA No. V9DR072Y')}</p>
      <p>{t('We offer a highly skilled staff, and certified technicians with over 55 years of experience.', 'Contamos con un personal altamente calificado y técnicos certificados con más de 55 años de experiencia.')}</p>
      <p>{t('Our goal is customer satisfaction and commitment to quality and reliability.', 'Nuestra meta es la satisfacción del cliente y el compromiso con la calidad y la confiabilidad.')}</p>
      <p>{t('We look forward to doing business with you.', 'Esperamos hacer negocios con usted.')}</p>
      <p class="call">{t(f'Give us a call TODAY at <a href="{PHONE_TEL}">305-392-6291</a>.', f'Llámenos HOY al <a href="{PHONE_TEL}">305-392-6291</a>.')}</p>
    </div>
    <figure class="photo">
      <a href="{L('shop', 'shop-entrance')}">{picture("shop-entrance", SHOP_BY_SLUG['shop-entrance'][3 if lang == 'en' else 4], sizes="(max-width: 860px) 100vw, 420px")}</a>
      <figcaption>{t('Aviation Workshop Entrance', 'Taller de aviación: entrada')}</figcaption>
    </figure>
  </div>
</section>
{quote_band(lang)}
"""
    return layout(lang, "home",
                  title=t("Avionics & Instrument Repair – FAA Repair Station, Miami, FL | Confidence Aviation",
                          "Reparación de aviónica e instrumentos – Estación reparadora FAA, Miami | Confidence Aviation"),
                  desc=t("FAA repair station No. V9DR072Y in Miami, Florida. Overhaul and repair capabilities: "
                         "Radio Class 1, 2 & 3 (communications, navigation, radar) and accessories. Request a repair quote.",
                         "Estación reparadora FAA No. V9DR072Y en Miami, Florida. Capacidades de reparación general y reparación: "
                         "Radio Class 1, 2 y 3 (comunicaciones, navegación, radar) y accesorios. Solicite una cotización."),
                  keywords=KEYWORDS_A, body=body)


def about(lang):
    t = tr(lang)
    L = lambda p, f="": url(lang, p, f)  # noqa: E731
    body = page_head(t("About Us", "Nosotros"), t("Our Company", "Nuestra empresa"),
                     t("Confidence Aviation, Inc. is an avionics and instrument repair station in Miami, Florida — "
                       "FAA repair station No. V9DR072Y, in business since 1998.",
                       "Confidence Aviation, Inc. es una estación reparadora de aviónica e instrumentos en Miami, Florida — "
                       "estación reparadora FAA No. V9DR072Y, en actividad desde 1998."),
                     cta_buttons(lang, (t("View Capabilities", "Ver capacidades"), L("capabilities")))) + f"""
<section class="section" aria-labelledby="profile">
  <div class="wrap split">
    <div>
      <h2 id="profile">{t('Company profile', 'Perfil de la empresa')}</h2>
      <dl class="spec">
        <dt>{t('Company', 'Empresa')}</dt><dd>Confidence Aviation, Inc.</dd>
        <dt>{t('Opened', 'Apertura')}</dt><dd>1998</dd>
        <dt>{t('Specialization', 'Especialidad')}</dt><dd>{t('Avionics &amp; Instruments', 'Aviónica e instrumentos')} — <a href="{L('capabilities')}">{t('Our Capabilities', 'Nuestras capacidades')}</a></dd>
        <dt>{t('FAA repair station No.', 'Estación reparadora FAA No.')}</dt><dd><span class="mono">V9DR072Y</span> — <a href="{L('certificates', 'air-agency-certificate')}"><span lang="en">Air Agency Certificate</span></a></dd>
        <dt>{t('FAA ratings', 'Habilitaciones FAA')}</dt><dd>Radio Class 1, 2 {t('&amp;', 'y')} 3; {t('Limited Ratings (accessories)', 'habilitaciones limitadas (accesorios)')}</dd>
        <dt>{t('EASA approval', 'Aprobación EASA')}</dt><dd><span class="mono">EASA.145.5139</span> — {t('date of issue 19 October 2004', 'fecha de emisión 19 de octubre de 2004')} — <a href="{L('certificates', 'easa-approval-certificate')}">{t('European Aviation Safety Agency Approval Certificate', 'Certificado de aprobación de la EASA')}</a></dd>
        <dt>{t('Experience', 'Experiencia')}</dt><dd>{t('Technicians with over 55 years of experience in aviation service', 'Técnicos con más de 55 años de experiencia en servicios de aviación')}</dd>
        <dt>{t('Presidents', 'Presidentes')}</dt><dd>Alex Hernandez, {t('President', 'Presidente')}; Roberto Perera, {t('President', 'Presidente')}</dd>
        <dt>{t('Business &amp; sales', 'Negocios y ventas')}</dt><dd>Maria Aniag Mikluscar, {t('Director of Business &amp; Sales', 'Dirección de Negocios y Ventas')}</dd>
        <dt>{t('Offices', 'Oficinas')}</dt><dd><address>Confidence Aviation, Inc., 7605 N.W. 50th Street, Miami, FL 33166</address></dd>
      </dl>
    </div>
    <figure class="photo">
      {picture("alex-and-robert", t("Alex Hernandez and Roberto Perera shaking hands", "Alex Hernandez y Roberto Perera estrechándose la mano"), sizes="289px", lazy=False)}
    </figure>
  </div>
</section>
<section class="section section--alt" aria-labelledby="letter">
  <div class="wrap">
    <div class="prose letter">
      <h2 id="letter">{t('A message from our Presidents', 'Mensaje de nuestros presidentes')}</h2>
      <p>{t('Confidence Aviation opened its doors in 1998, and customer satisfaction has always been our number one priority. We are FAA &amp; JAA certified, and take pride in providing quality service to all of our customers.',
            'Confidence Aviation abrió sus puertas en 1998 y la satisfacción del cliente siempre ha sido nuestra prioridad número uno. Estamos certificados por la FAA y JAA, y nos enorgullece brindar un servicio de calidad a todos nuestros clientes.')}</p>
      <p>{t('Confidence Aviation is proud to state that our technicians have over 55 years of experience in aviation service.',
            'Confidence Aviation se enorgullece de afirmar que nuestros técnicos tienen más de 55 años de experiencia en servicios de aviación.')}</p>
      <p>{t('Thank you for taking the time to visit us on the web. We encourage you to visit our offices and see for yourself just how confident we are that we can fulfill all your aviation repair needs. We look forward to doing business with you in the future.',
            'Gracias por tomarse el tiempo de visitarnos en la web. Le invitamos a visitar nuestras oficinas y comprobar por sí mismo cuán seguros estamos de poder satisfacer todas sus necesidades de reparación aeronáutica. Esperamos hacer negocios con usted en el futuro.')}</p>
      <div class="signature">
        <p>{t('Sincerely,', 'Atentamente,')}</p>
        <p class="names">Alex Hernandez, {t('President', 'Presidente')}</p>
        <p class="names">Roberto Perera, {t('President', 'Presidente')}</p>
      </div>
      <p class="note history-note">{t('This letter is reproduced from the company’s original website (©2003 - 2011). For the certification documents on file, with the dates printed on them, see <a href="' + L('certificates') + '">Our Certificates</a>.',
                                     'Esta carta se reproduce del sitio web original de la empresa (©2003 - 2011). Para ver los documentos de certificación disponibles, con las fechas que figuran en ellos, consulte <a href="' + L('certificates') + '">Nuestros certificados</a>.')}</p>
    </div>
  </div>
</section>
<section class="section" aria-labelledby="history">
  <div class="wrap"><div class="prose">
    <h2 id="history">{t('Website history', 'Historia del sitio web')}</h2>
    <p>{t('Confidence Aviation’s previous website (©2003 - 2011 Confidence Aviation, Inc.) was created by <a href="http://www.wintertek.com" rel="noopener">wintertek</a>. Its content is preserved on this site.',
          'El sitio web anterior de Confidence Aviation (©2003 - 2011 Confidence Aviation, Inc.) fue creado por <a href="http://www.wintertek.com" rel="noopener">wintertek</a>. Su contenido se conserva en este sitio.')}</p>
  </div></div>
</section>
{quote_band(lang)}
"""
    return layout(lang, "about", crumbs=[(t("About Us", "Nosotros"), L("about"))],
                  title=t("About Us – Our Company | Confidence Aviation, Inc., Miami, FL",
                          "Nosotros – Nuestra empresa | Confidence Aviation, Inc., Miami, FL"),
                  desc=t("Confidence Aviation opened its doors in 1998 in Miami, Florida. FAA repair station No. V9DR072Y "
                         "for avionics and instruments; technicians with over 55 years of experience in aviation service.",
                         "Confidence Aviation abrió sus puertas en 1998 en Miami, Florida. Estación reparadora FAA No. V9DR072Y "
                         "de aviónica e instrumentos; técnicos con más de 55 años de experiencia en servicios de aviación."),
                  keywords=KEYWORDS_A, body=body)


def capabilities(lang):
    t = tr(lang)
    L = lambda p, f="": url(lang, p, f)  # noqa: E731
    thumbs = gallery(lang, SHOP, "caps", compact=True, link_to=L("shop"))
    body = page_head(t("Capabilities", "Capacidades"), t("Our Capabilities", "Nuestras capacidades"),
                     t("Avionics &amp; Instruments — FAA Certified Repair Station",
                       "Aviónica e instrumentos — Estación reparadora certificada por la FAA"),
                     cta_buttons(lang)) + f"""
<nav class="section section--tight toc" aria-labelledby="toc-h">
  <div class="wrap"><h2 id="toc-h" class="visually-hidden">{t('Capability areas on this page', 'Áreas de capacidad en esta página')}</h2>{cap_cards(lang)}</div>
</nav>
<section class="section section--alt" aria-labelledby="ratings">
  <div class="wrap split">
    <div>
      <h2 id="ratings">{t('Ratings and limitations', 'Habilitaciones y limitaciones')}</h2>
      <p>{t('Confidence Aviation is authorized the following ratings and limitations:', 'Confidence Aviation está autorizada para las siguientes habilitaciones y limitaciones:')}</p>
      <h3 id="class-ratings">{t('Class Ratings', 'Habilitaciones de clase (<span lang="en">Class Ratings</span>)')}</h3>
      {ratings_list(lang)}
      <h3 id="accessories">{icon('valve')} {t('Limited Ratings', 'Habilitaciones limitadas (<span lang="en">Limited Ratings</span>)')}</h3>
      <p>{t('Many accessories including Pneumatic Valves and Lights.', 'Muchos accesorios, incluidas válvulas neumáticas y luces.')}</p>
      <div class="notice"><p>{t(f'Please call our offices at <a href="{PHONE_TEL}">1-305-392-6291</a> for a complete list.',
                                f'Llame a nuestras oficinas al <a href="{PHONE_TEL}">1-305-392-6291</a> para obtener una lista completa.')}</p></div>
    </div>
    <div>
      <figure class="photo">{picture("hugo-in-the-shop", t("Hugo at a test bench in the shop", "Hugo en un banco de pruebas del taller"), sizes="232px")}</figure>
      <div class="card mt-2">
        <h3>{t('Where these ratings are documented', 'Dónde constan estas habilitaciones')}</h3>
        <p>{t(f'The class ratings and limited ratings are listed in the FAA <a href="{L("certificates", "operations-specifications")}">Operations Specifications (A003. Ratings and Limitations)</a> and the <a href="{L("certificates", "air-agency-certificate")}">Air Agency Certificate</a>, No. <span class="mono">V9DR072Y</span>.',
              f'Las habilitaciones de clase y las habilitaciones limitadas figuran en las <a href="{L("certificates", "operations-specifications")}"><span lang="en">Operations Specifications</span> (A003. <span lang="en">Ratings and Limitations</span>)</a> de la FAA y en el <a href="{L("certificates", "air-agency-certificate")}"><span lang="en">Air Agency Certificate</span></a> No. <span class="mono">V9DR072Y</span>.')}</p>
      </div>
    </div>
  </div>
</section>
<section class="section" aria-labelledby="avionics-instruments">
  <div class="wrap">
    <h2 id="avionics-instruments">{icon('gauge', 'icon icon--lg')} {t('Avionics &amp; Instruments', 'Aviónica e instrumentos')}</h2>
    <p class="prose">{t('Avionics repair shop Miami Florida. Providing OEM alternative repairs for Boeing, Bendix/King, Honeywell, Sperry, Collins aircraft instrument panels and valves.',
                        'Taller de reparación de aviónica en Miami, Florida. Reparaciones como alternativa al OEM para paneles de instrumentos y válvulas de aeronaves Boeing, Bendix/King, Honeywell, Sperry, Collins.')}</p>
    <dl class="spec spec--compact">
      <dt>{t('Scope', 'Alcance')}</dt><dd>{t('Aircraft instruments, instrument panels and valves', 'Instrumentos, paneles de instrumentos y válvulas de aeronaves')}</dd>
      <dt>{t('Basis', 'Modalidad')}</dt><dd>{t('OEM alternative repair station', 'Estación reparadora alternativa al OEM')}</dd>
      <dt>{t('Location', 'Ubicación')}</dt><dd>{t('Miami, Florida', 'Miami, Florida')}</dd>
    </dl>
    <h3>{t('Manufacturers referenced', 'Fabricantes mencionados')}</h3>
    <ul class="tag-list"><li>Boeing</li><li>Bendix/King</li><li>Honeywell</li><li>Sperry</li><li>Collins</li></ul>
    <p class="note">{t('Manufacturer names identify the equipment concerned and do not indicate manufacturer authorization.',
                       'Los nombres de los fabricantes identifican los equipos y no indican autorización del fabricante.')}</p>
  </div>
</section>
<section class="section section--alt" aria-labelledby="benches">
  <div class="wrap">
    <div class="section__head"><h2 id="benches">{t('Test benches and equipment in our shop', 'Bancos y equipos de prueba de nuestro taller')}</h2><a class="more" href="{L('shop')}">{t('Shop Tour', 'Recorrido del taller')}</a></div>
    <div class="gallery-four">{thumbs}</div>
  </div>
</section>
{quote_band(lang, t('Is your unit covered? Request a Repair Quote', '¿Su unidad está cubierta? Solicite una cotización de reparación'))}
"""
    return layout(lang, "capabilities", crumbs=[(t("Capabilities", "Capacidades"), L("capabilities"))],
                  title=t("Capabilities – Radio Class 1, 2 & 3 and Accessory Ratings | Confidence Aviation",
                          "Capacidades – Habilitaciones Radio Class 1, 2 y 3 y accesorios | Confidence Aviation"),
                  desc=t("FAA Radio Class 1 (communications), Class 2 (navigation) and Class 3 (radar) ratings, limited "
                         "accessory ratings, and OEM alternative repairs for Boeing, Bendix/King, Honeywell, Sperry and Collins "
                         "instrument panels and valves. Miami, Florida.",
                         "Habilitaciones FAA Radio Class 1 (comunicaciones), Class 2 (navegación) y Class 3 (radar), habilitaciones "
                         "limitadas de accesorios y reparaciones como alternativa al OEM para paneles de instrumentos y válvulas "
                         "Boeing, Bendix/King, Honeywell, Sperry y Collins. Miami, Florida."),
                  body=body)


def doc_sections(lang):
    t = tr(lang)
    out = []
    for slug, title, orig, es_title, short, d_en, d_es in DOCS:
        spec = "".join(f"<dt>{en if lang == 'en' else es}</dt><dd>{v}</dd>" for en, es, v in SPEC[slug])
        size_kb = round((ROOT / "legacy" / "original-site" / orig).stat().st_size / 1024)
        ext = orig.rsplit(".", 1)[1].upper()
        h = f"<h2>{title}</h2>" if lang == "en" else f'<h2><span lang="en">{title}</span></h2><p class="note">{es_title}</p>'
        links = (f'<li><a href="{full_src(slug)}" data-lightbox="docs" data-caption="{e(title)}">{icon("doc", "icon icon--sm")}{t("View full size", "Ver en tamaño completo")}</a></li>'
                 f'<li><a href="/{e(orig)}" download>{icon("arrow", "icon icon--sm")}{t("Download original file", "Descargar archivo original")} ({ext}, {size_kb} KB)</a></li>')
        summ = t("Full text of the document", "Texto completo del documento (en inglés, tal como fue emitido)")
        thumb_alt = t(f"{title} — scanned document", f"{title} — documento escaneado")
        out.append(f"""
<article class="doc" id="{slug}" aria-labelledby="{slug}-h">
  <div class="doc__image">
    <a href="{full_src(slug)}" data-lightbox="docs" data-caption="{e(title)}">{doc_thumb(slug, thumb_alt)}</a>
    <ul class="doc__links">{links}</ul>
  </div>
  <div>
    <div id="{slug}-h">{h}</div>
    <p class="doc-date">{t(d_en, d_es)}</p>
    <dl class="spec">{spec}</dl>
    <details><summary>{summ}</summary><div class="transcript" lang="en">{TRANSCRIPT[slug]}</div></details>
  </div>
</article>""")
    return "".join(out)


def doc_table(lang):
    t = tr(lang)
    rows = "".join(
        f'<tr><th scope="row"><a href="#{slug}"{LANG_EN if lang == "es" else ""}>{title}</a>'
        f'{"" if lang == "en" else f"<br><small>{es}</small>"}</th>'
        f'<td>{t(*DOC_ISSUER[slug])}</td><td class="mono">{short}</td><td>{t(d_en, d_es)}</td></tr>'
        for slug, title, _o, es, short, d_en, d_es in DOCS)
    return (f'<div class="table-wrap"><table class="doc-table"><caption class="visually-hidden">{t("Certificate List", "Lista de certificados")}</caption>'
            f'<thead><tr><th scope="col">{t("Document", "Documento")}</th><th scope="col">{t("Issued by", "Emitido por")}</th>'
            f'<th scope="col">{t("Number / reference", "Número / referencia")}</th><th scope="col">{t("Date on document", "Fecha en el documento")}</th></tr></thead>'
            f'<tbody>{rows}</tbody></table></div>')


def certificates(lang):
    t = tr(lang)
    L = lambda p, f="": url(lang, p, f)  # noqa: E731
    body = page_head(t("Certificates", "Certificados"), t("Our Certificates", "Nuestros certificados"),
                     t("FAA repair station No. V9DR072Y", "Estación reparadora FAA No. V9DR072Y")) + f"""
<section class="section" aria-labelledby="list">
  <div class="wrap">
    <h2 id="list">{t('Certificate List', 'Lista de certificados')}</h2>
    {doc_table(lang)}
    <div class="notice mt-2"><p>{t(
        f'The document images below are the certificates as displayed on our previous website. Dates are those printed on each document. Text transcriptions are provided for accessibility and search; the document images are the authoritative record. For the current status of any certificate, contact us at <a href="mailto:{EMAIL}">{EMAIL}</a>.',
        f'Las imágenes siguientes son los certificados tal como se mostraban en nuestro sitio web anterior. Las fechas son las que figuran en cada documento. Los documentos originales están en inglés; sus datos y su texto completo se reproducen tal como fueron emitidos. Las imágenes de los documentos son el registro oficial. Para conocer el estado actual de cualquier certificado, escríbanos a <a href="mailto:{EMAIL}">{EMAIL}</a>.')}</p></div>
    {doc_sections(lang)}
  </div>
</section>
<section class="section section--alt" aria-labelledby="cert-contact">
  <div class="wrap split">
    <div>
      <h2 id="cert-contact">{t('Questions about our certification?', '¿Preguntas sobre nuestra certificación?')}</h2>
      <p>{t('Contact our office for current certificate and approval information.', 'Comuníquese con nuestra oficina para obtener información actual sobre certificados y aprobaciones.')}</p>
      <div class="actions"><a class="btn btn--primary" href="{L('contact')}">{t('Contact Confidence Aviation', 'Contactar a Confidence Aviation')}</a><a class="btn btn--outline" href="{PHONE_TEL}">{t('Call', 'Llamar al')} {PHONE}</a></div>
    </div>
  </div>
</section>
"""
    return layout(lang, "certificates", crumbs=[(t("Certificates", "Certificados"), L("certificates"))],
                  title=t("Our Certificates – FAA Air Agency Certificate V9DR072Y & EASA.145.5139 | Confidence Aviation",
                          "Nuestros certificados – FAA V9DR072Y y EASA.145.5139 | Confidence Aviation"),
                  desc=t("Confidence Aviation certificates: FAA Air Agency Certificate No. V9DR072Y (issued 1998), European "
                         "Aviation Safety Agency Approval Certificate EASA.145.5139 (issued 2004) and FAA Operations "
                         "Specifications A003 — images, key details and full text.",
                         "Certificados de Confidence Aviation: Air Agency Certificate de la FAA No. V9DR072Y (emitido en 1998), "
                         "certificado de aprobación de la EASA EASA.145.5139 (emitido en 2004) y Operations Specifications A003 "
                         "de la FAA — imágenes, datos clave y texto completo."),
                  body=body, og_image="/assets/img/air-agency-certificate-545.jpg")


def shop(lang):
    t = tr(lang)
    L = lambda p, f="": url(lang, p, f)  # noqa: E731
    body = page_head(t("Shop Tour", "Recorrido del taller"), t("Shop Tour", "Recorrido del taller"),
                     t("Photos of the Confidence Aviation shop and test benches. Select an image to enlarge it; use the arrow keys to move between images.",
                       "Fotos del taller y los bancos de prueba de Confidence Aviation. Seleccione una imagen para ampliarla; use las teclas de flecha para pasar de una imagen a otra.")) + f"""
<section class="section" aria-labelledby="images">
  <div class="wrap">
    <h2 id="images">{t('Images', 'Imágenes')}</h2>
    {gallery(lang, SHOP, "shop", with_ids=True, eager=2)}
  </div>
</section>
<section class="section section--alt">
  <div class="wrap split split--reverse">
    <figure class="photo">{picture("roberto-in-shop", t("Roberto at a rack of test equipment in the shop", "Roberto junto a un bastidor de equipos de prueba en el taller"), sizes="(max-width: 860px) 100vw, 407px")}</figure>
    <div class="prose">
      <h2>{t('Visit our offices', 'Visite nuestras oficinas')}</h2>
      <address class="address-block">{"<br>".join(ADDRESS_LINES)}</address>
      <p>{t('Phone', 'Teléfono')}: <a href="{PHONE_TEL}">{PHONE}</a></p>
      <div class="actions"><a class="btn btn--outline" href="{L('contact', 'directions')}">{t('Directions', 'Cómo llegar')}</a></div>
    </div>
  </div>
</section>
{quote_band(lang)}
"""
    return layout(lang, "shop", crumbs=[(t("Shop Tour", "Recorrido del taller"), L("shop"))],
                  title=t("Shop Tour – Avionics Test Benches | Confidence Aviation, Miami, FL",
                          "Recorrido del taller – Bancos de prueba de aviónica | Confidence Aviation, Miami, FL"),
                  desc=t("Photos of the Confidence Aviation shop in Miami, Florida: DME transponder, radar, NAV/COMM and altimeter "
                         "benches, altimeter test set, HF antenna, radar indicators and radio altimeters.",
                         "Fotos del taller de Confidence Aviation en Miami, Florida: bancos de DME y transpondedor, radar, NAV/COMM y "
                         "altímetro, equipo de prueba de altímetros, antena HF, indicadores de radar y radioaltímetros."),
                  body=body)


def quote_form(lang):
    t = tr(lang)
    req = f' <span class="req">({t("required", "obligatorio")})</span>'

    def field(fid, label, *, kind="input", typ="text", required=False, auto="", hint="", extra=""):
        hint_html = f'<span class="hint" id="{fid}-hint">{hint}</span>' if hint else ""
        described = f' aria-describedby="{fid}-hint {fid}-err"' if hint else f' aria-describedby="{fid}-err"'
        r = " required" if required else ""
        a = f' autocomplete="{auto}"' if auto else ""
        if kind == "textarea":
            ctl = f'<textarea id="{fid}" name="{fid[2:]}"{r}{described}{extra}></textarea>'
        elif kind == "select":
            ctl = f'<select id="{fid}" name="{fid[2:]}"{described}{extra}>{hint and ""}</select>'
        else:
            ctl = f'<input id="{fid}" name="{fid[2:]}" type="{typ}"{a}{r}{described}{extra}>'
        return (f'<div class="field"><label for="{fid}">{label}{req if required else ""}</label>{hint_html}{ctl}'
                f'<span class="field-error" id="{fid}-err"></span></div>')

    work = "".join(f'<option value="{e(v)}">{lab}</option>' for v, lab in (
        (t("Repair", "Reparación"), t("Repair", "Reparación")),
        (t("Overhaul", "Reparación general (overhaul)"), t("Overhaul", "Reparación general (overhaul)")),
        (t("Not sure / other", "No estoy seguro / otro"), t("Not sure / other", "No estoy seguro / otro"))))
    return f"""
<form id="contact-form" class="quote-form" action="mailto:{EMAIL}" method="post" enctype="text/plain" novalidate aria-labelledby="quote">
  <h2 id="quote" tabindex="-1">{UI[lang]['cta']}</h2>
  <p class="note">{t(f'Sending this form opens your own email program with a message addressed to {EMAIL}. Nothing is sent until you send that email. You can attach photos, work orders or other documents there.',
                     f'Al enviar este formulario se abre su propio programa de correo con un mensaje dirigido a {EMAIL}. No se envía nada hasta que usted envíe ese correo. Allí puede adjuntar fotos, órdenes de trabajo u otros documentos.')}</p>
  <div class="form-errors" role="alert" aria-live="assertive" hidden></div>
  <fieldset>
    <legend>{t('Your details', 'Sus datos')}</legend>
    <div class="field-row">
      {field('f-name', t('Name', 'Nombre'), required=True, auto='name')}
      {field('f-company', t('Company / operator', 'Empresa / operador'), auto='organization')}
    </div>
    <div class="field-row">
      {field('f-email', t('Email', 'Correo electrónico'), typ='email', required=True, auto='email')}
      {field('f-phone', t('Phone', 'Teléfono'), typ='tel', auto='tel')}
    </div>
  </fieldset>
  <fieldset>
    <legend>{t('Unit details', 'Datos de la unidad')}</legend>
    <div class="field-row">
      {field('f-manufacturer', t('Manufacturer', 'Fabricante'), required=True)}
      {field('f-model', t('Model / description', 'Modelo / descripción'))}
    </div>
    <div class="field-row">
      {field('f-part', t('Part number', 'Número de parte'), required=True, extra=' spellcheck="false"')}
      {field('f-serial', t('Serial number(s)', 'Número(s) de serie'), extra=' spellcheck="false"')}
    </div>
    <div class="field-row">
      {field('f-qty', t('Quantity', 'Cantidad'), typ='number', extra=' min="1" step="1" inputmode="numeric" value="1"')}
      {field('f-aircraft', t('Aircraft type / registration', 'Tipo de aeronave / matrícula'))}
    </div>
  </fieldset>
  <fieldset>
    <legend>{t('Request', 'Solicitud')}</legend>
    <div class="field"><label for="f-work">{t('Work requested', 'Trabajo solicitado')}</label><select id="f-work" name="work">{work}</select></div>
    <div class="field field--check"><input id="f-aog" name="aog" type="checkbox" value="{t('AOG - aircraft on ground', 'AOG - aeronave en tierra')}"><label for="f-aog">{t('This unit is for an aircraft on ground (AOG)', 'Esta unidad es para una aeronave en tierra (AOG)')}</label></div>
    {field('f-message', t('Reported fault / details', 'Falla reportada / detalles'), kind='textarea', required=True,
           hint=t('Describe the reported fault or the work required, and any documentation you need back.',
                  'Describa la falla reportada o el trabajo requerido, y la documentación que necesita.'))}
  </fieldset>
  <button class="btn btn--primary" type="submit">{icon('mail', 'icon icon--sm')}{t('Compose quote request email', 'Redactar correo de solicitud')}</button>
  <p class="form-status" role="status" aria-live="polite"></p>
  <p class="note">{t(f'Prefer to call? <a href="{PHONE_TEL}">{PHONE}</a> · Fax {FAX}', f'¿Prefiere llamar? <a href="{PHONE_TEL}">{PHONE}</a> · Fax {FAX}')}</p>
</form>"""


def contact(lang):
    t = tr(lang)
    L = lambda p, f="": url(lang, p, f)  # noqa: E731
    airports = [("MIA", t("Get directions from Miami International (MIA) Airport", "Cómo llegar desde el Aeropuerto Internacional de Miami (MIA)")),
                ("FLL", t("Get directions from Fort Lauderdale International (FLL) Airport", "Cómo llegar desde el Aeropuerto Internacional de Fort Lauderdale (FLL)")),
                ("FXE", t("Get directions from Fort Lauderdale Executive (FXE) Airport", "Cómo llegar desde el Aeropuerto Ejecutivo de Fort Lauderdale (FXE)"))]
    mq = dict(MAPQUEST)
    here = t("HERE", "AQUÍ")
    dirs = "".join(
        f'<li>{label} &gt; <a href="{mq[code]}" rel="noopener" target="_blank">{here}<span class="visually-hidden"> – '
        f'{t(f"directions from {code} (MapQuest, opens in a new tab)", f"indicaciones desde {code} (MapQuest, se abre en una pestaña nueva)")}</span></a></li>'
        for code, label in airports)
    body = page_head(t("Contact", "Contacto"), t("Contact Info", "Información de contacto"),
                     t("Request a repair quote, or contact our office in Miami, Florida by phone, fax or email.",
                       "Solicite una cotización de reparación o comuníquese con nuestra oficina en Miami, Florida por teléfono, fax o correo electrónico.")) + f"""
<section class="section">
  <div class="wrap contact-grid">
    <div class="contact-info">
      <div class="card contact-card">
        <address class="address-block">{icon('pin')}<span>{"<br>".join(ADDRESS_LINES)}</span></address>
        <ul class="contact-list">
          <li><span class="k">{t('Phone', 'Teléfono')}</span><span class="v"><a href="{PHONE_TEL}">{PHONE}</a></span></li>
          <li><span class="k">Fax</span><span class="v">{FAX}</span></li>
          <li><span class="k">{t('Email', 'Correo')}</span><span class="v"><a href="mailto:{EMAIL}">{EMAIL}</a></span></li>
        </ul>
        <p>{t('Feel free to contact our Director of Business &amp; Sales<br><strong>Maria Aniag Mikluscar</strong>',
              'No dude en contactar a <strong>Maria Aniag Mikluscar</strong>, a cargo de la Dirección de Negocios y Ventas (<span lang="en">Director of Business &amp; Sales</span>).')}</p>
      </div>
      <h2 id="directions">{t('Directions', 'Cómo llegar')}</h2>
      <ul class="link-list link-list--single">
        {dirs}
        <li><a href="{GMAPS_DIR}" rel="noopener" target="_blank">{t('Directions to 7605 N.W. 50th Street, Miami, FL 33166 in Google Maps', 'Cómo llegar a 7605 N.W. 50th Street, Miami, FL 33166 en Google Maps')}<span class="visually-hidden"> {t('(opens in a new tab)', '(se abre en una pestaña nueva)')}</span></a></li>
      </ul>
      <figure class="photo photo--small mt-3">{picture("reception", t("Reception desk", "Recepción"), sizes="248px")}</figure>
    </div>
    <div class="card card--form">{quote_form(lang)}</div>
  </div>
</section>
"""
    return layout(lang, "contact", crumbs=[(t("Contact", "Contacto"), L("contact"))],
                  title=t("Contact & Repair Quotes – 7605 N.W. 50th Street, Miami, FL | Confidence Aviation",
                          "Contacto y cotizaciones – 7605 N.W. 50th Street, Miami, FL | Confidence Aviation"),
                  desc=t("Request a repair quote from Confidence Aviation, Inc., 7605 N.W. 50th Street, Miami, FL 33166. "
                         "Phone 1-305-392-6291, fax 1-305-392-6292, info@confidenceaviation.com. Directions from MIA, FLL and FXE.",
                         "Solicite una cotización de reparación a Confidence Aviation, Inc., 7605 N.W. 50th Street, Miami, FL 33166. "
                         "Teléfono 1-305-392-6291, fax 1-305-392-6292, info@confidenceaviation.com. Cómo llegar desde MIA, FLL y FXE."),
                  body=body)


# ---------------------------------------------------------------- special files
def not_found():
    body = f"""
<section class="section">
  <div class="wrap prose">
    <p class="error-code">404</p>
    <h1>Page not found</h1>
    <p>The page you requested does not exist or has moved. Every page from our previous website is still available at its original address:</p>
    <ul>{"".join(f'<li><a href="{url("en", p)}">{UI["en"]["nav"][p]}</a></li>' for p in PAGES)}</ul>
    <div lang="es">
      <h2>Página no encontrada</h2>
      <p>La página solicitada no existe o se ha movido.</p>
      <ul>{"".join(f'<li><a href="{url("es", p)}">{UI["es"]["nav"][p]}</a></li>' for p in PAGES)}</ul>
    </div>
    <div class="actions"><a class="btn btn--primary" href="{url('en', 'contact', 'quote')}">{UI['en']['cta']}</a>
    <a class="btn btn--outline" href="{PHONE_TEL}">{PHONE}</a></div>
    <p>Phone / Teléfono: <a href="{PHONE_TEL}">{PHONE}</a> · <a href="mailto:{EMAIL}">{EMAIL}</a></p>
  </div>
</section>"""
    return layout("en", "home", title="Page not found | Confidence Aviation", desc="Page not found.", body=body, noindex=True)


def relativize(page_html, depth):
    """Make site-internal links relative so the site works at any base path
    (domain root, GitHub Pages project URL, local web server). Absolute
    https:// URLs (canonical, hreflang, Open Graph, JSON-LD) are untouched."""
    prefix = "../" * depth
    out = re.sub(r'((?:href|src|srcset|action)=")/(?!/)', lambda m: m.group(1) + prefix, page_html)
    out = re.sub(r'(srcset="[^"]*)', lambda m: m.group(1).replace(", /assets", ", " + prefix + "assets"), out)
    return out.replace('href=""', 'href="./"')


def redirect_stub(target):
    """Static fallback for hosts that ignore .htaccess: the old URL keeps working."""
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Confidence Aviation – Avionics &amp; Instrument Repair</title>
<link rel="canonical" href="{SITE}/">
<meta name="robots" content="noindex, follow">
<meta http-equiv="refresh" content="0; url={target}">
</head><body><p>This page has moved to <a href="{target}">{SITE}/</a>.</p></body></html>
"""


def sitemap():
    rows = []
    for p in PAGES:
        for lang in ("en", "es"):
            alts = "".join(f'<xhtml:link rel="alternate" hreflang="{l}" href="{SITE}{url(l, p)}"/>' for l in ("en", "es"))
            alts += f'<xhtml:link rel="alternate" hreflang="x-default" href="{SITE}{url("en", p)}"/>'
            rows.append(f"  <url><loc>{SITE}{url(lang, p)}</loc>{alts}</url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
            + "\n".join(rows) + "\n</urlset>\n")


ROBOTS = f"""User-agent: *
Allow: /

Sitemap: {SITE}/sitemap.xml
"""


def main():
    global ASSET_V
    (PUB / "assets" / "css").mkdir(parents=True, exist_ok=True)
    (PUB / "assets" / "js").mkdir(parents=True, exist_ok=True)
    (PUB / "es").mkdir(exist_ok=True)
    ASSET_V = {}
    for kind, name in (("css", "site.css"), ("js", "site.js")):
        data = (SRC / "assets" / kind / name).read_bytes()
        (PUB / "assets" / kind / name).write_bytes(data)
        ASSET_V[kind] = hashlib.sha256(data).hexdigest()[:10]

    # The CSP in src/htaccess allows exactly one inline script, by hash. Fail loudly if they drift apart.
    import base64
    inline = 'document.documentElement.className="js"'
    digest = base64.b64encode(hashlib.sha256(inline.encode()).digest()).decode()
    if f"'sha256-{digest}'" not in (SRC / "htaccess").read_text():
        raise SystemExit("CSP hash in src/htaccess does not match the inline script in layout()")

    builders = {"home": home, "about": about, "capabilities": capabilities,
                "certificates": certificates, "shop": shop, "contact": contact}
    pages = {}
    for lang in ("en", "es"):
        for p in PAGES:
            pages[("es/" if lang == "es" else "") + FILES[p]] = builders[p](lang)
    pages.update({
        "404.html": not_found(),
        "index.htm": redirect_stub("./"),
        "sitemap.xml": sitemap(),
        "robots.txt": ROBOTS,
        "site.webmanifest": json.dumps({
            "name": "Confidence Aviation, Inc.", "short_name": "Confidence Aviation",
            "icons": [{"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
                      {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"}],
            "theme_color": "#03204a", "background_color": "#ffffff", "display": "browser"}, indent=1),
    })
    for name, content in pages.items():
        if name.endswith((".html", ".htm")) and name not in ("404.html", "index.htm"):
            content = relativize(content, name.count("/"))
        (PUB / name).write_text(content, encoding="utf-8")
    shutil.copy2(SRC / "htaccess", PUB / ".htaccess")
    print(f"built {len(pages)} files into {PUB.relative_to(ROOT)}/")


ASSET_V = {"css": "", "js": ""}

if __name__ == "__main__":
    main()
